---
name: Draft

on:
  pull_request:
    types: [review_requested, ready_for_review, synchronize]
  push:
    branches:
      - main
    paths-ignore:
      - "packages/web/**"

jobs:
  yamellint-misspell-hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
