---
name: PR

on:
  pull_request:
    types: [opened, ready_for_review]
  push:
    branches:
      - main
    paths-ignore:
      - "packages/web/**"

jobs:
  yamellint-misspell-hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
